name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: true

    steps:
    - name: Install IPFS
      run: |
        IPFS_BUILD=linux
        if [[ ${{ matrix.os }} =~ macos-[a-zA-Z0-9_] ]]; then IPFS_BUILD=darwin; fi
        mkdir $HOME/opt
        pushd $HOME/opt
        curl -s -L https://dist.ipfs.io/go-ipfs/v0.4.22/go-ipfs_v0.4.22_$IPFS_BUILD-amd64.tar.gz | tar zxf - go-ipfs/ipfs
        popd
        $HOME/opt/go-ipfs/ipfs init
        echo "::add-path::$HOME/opt/go-ipfs"
      timeout-minutes: 2
    - name: Run commands
      run: |
        echo Hello world!
        ipfs daemon & sleep 5
        ipfs id
      timeout-minutes: 5   
    - name: Summary
      run: |
        echo Bye!
