name: Manual Build

on: workflow_dispatch

jobs:
  bar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Make a change
        run: |
          date > now.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
