name: Manual Build

on:
  schedule:
    - cron: "* */6 * * *"
  workflow_dispatch:  

jobs:
  bar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Make a change
        run: |
          date > now.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Automatic update
          labels: automatic
          branch: automatic-pr
